# Generated by Django 3.0.2 on 2020-12-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='mob_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
